Comments
dotnet/Docker.DotNet pull request #612
Opened 2023-02-24 18:50 UTC by mikeblas

2023-02-25 10:58 UTC, HofmeisterAn requested changes

2023-02-25 10:58 UTC, HofmeisterAn commented on src/Docker.DotNet/Endpoints/IContainerOperations.cs
> +        /// <br/>The corresponding command in the Docker CLI is <c>docker logs</c>.</remarks>
```suggestion
        /// <br/>The corresponding commands in the Docker CLI are <c>docker logs</c> and <c>docker container logs</c>.</remarks>
```

Both are valid Docker CLI commands.

2023-02-25 10:58 UTC, HofmeisterAn commented on src/Docker.DotNet/Endpoints/IContainerOperations.cs
> +        /// <br/>The corresponding command in the Docker CLI is <c>docker logs</c>.</remarks>
```suggestion
        /// <br/>The corresponding commands in the Docker CLI are <c>docker logs</c> and <c>docker container logs</c>.</remarks>
```

2023-02-25 10:58 UTC, HofmeisterAn commented on src/Docker.DotNet/Endpoints/IContainerOperations.cs
> +        /// <remarks>The corresponding command in the Docker CLI is <c>docker logs</c>.</remarks>
```suggestion
        /// <remarks>The corresponding commands in the Docker CLI are <c>docker logs</c> and <c>docker container logs</c>.</remarks>
```

2023-02-25 20:20 UTC, mikeblas commented on src/Docker.DotNet/Endpoints/IContainerOperations.cs
> +        /// <br/>The corresponding command in the Docker CLI is <c>docker logs</c>.</remarks>
fixed

2023-02-25 20:20 UTC, mikeblas commented on src/Docker.DotNet/Endpoints/IContainerOperations.cs
> +        /// <br/>The corresponding command in the Docker CLI is <c>docker logs</c>.</remarks>
fixed

2023-02-25 20:21 UTC, mikeblas commented on src/Docker.DotNet/Endpoints/IContainerOperations.cs
> +        /// <remarks>The corresponding command in the Docker CLI is <c>docker logs</c>.</remarks>
fixed

2023-02-26 10:28 UTC, HofmeisterAn requested changes

2023-02-26 10:28 UTC, HofmeisterAn commented on src/Docker.DotNet/Endpoints/IContainerOperations.cs
> +        /// <br/>The corresponding command in the Docker CLI are </c> <c>docker logs</c> and <c>docker container logs</c>.</remarks>
```suggestion
        /// <br/>The corresponding command in the Docker CLI are <c>docker logs</c> and <c>docker container logs</c>.</remarks>
```

2023-02-26 10:28 UTC, HofmeisterAn commented on src/Docker.DotNet/Endpoints/IContainerOperations.cs
> +        /// <br/>The corresponding command in the Docker CLI are </c> <c>docker logs</c> and <c>docker container logs</c>.</remarks>
```suggestion
        /// <br/>The corresponding command in the Docker CLI are <c>docker logs</c> and <c>docker container logs</c>.</remarks>
```

2023-02-26 10:28 UTC, HofmeisterAn commented on src/Docker.DotNet/Endpoints/IContainerOperations.cs
> +        /// <br/>The corresponding command in the Docker CLI are </c> <c>docker logs</c> and <c>docker container logs</c>.</remarks>
```suggestion
        /// <remarks>The corresponding command in the Docker CLI are <c>docker logs</c> and <c>docker container logs</c>.</remarks>
```

2024-10-30 17:39 UTC, merged